name: login_ui
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Rubik Medium
      fonts:
        - asset: fonts/rubik_medium.ttf
    - family: Rubik Regular
      fonts:
        - asset: fonts/rubik_regular.ttf